version: 2.1
jobs:
  build:
    docker:
       -image: circleci/node:9.1
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn
      - run: yarn build
workflows:
  version:2.1
  drone:
    jobs:
      - build